name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21 and Maven
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Verify Java Version
      run: java -version
    - name: Verify Maven Version
      run: mvn --version
    - name: Create Maven Toolchains file
      run: |
        mkdir -p ~/.m2
        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > ~/.m2/toolchains.xml
        echo "<toolchains>" >> ~/.m2/toolchains.xml
        echo "  <toolchain>" >> ~/.m2/toolchains.xml
        echo "    <type>jdk</type>" >> ~/.m2/toolchains.xml
        echo "    <provides>" >> ~/.m2/toolchains.xml
        echo "      <version>21</version>" >> ~/.m2/toolchains.xml
        echo "      <vendor>temurin</vendor>" >> ~/.m2/toolchains.xml
        echo "    </provides>" >> ~/.m2/toolchains.xml
        echo "    <configuration>" >> ~/.m2/toolchains.xml
        echo "      <jdkHome>${JAVA_HOME}</jdkHome>" >> ~/.m2/toolchains.xml
        echo "    </configuration>" >> ~/.m2/toolchains.xml
        echo "  </toolchain>" >> ~/.m2/toolchains.xml
        echo "</toolchains>" >> ~/.m2/toolchains.xml
      shell: bash
    
    # --- Selenium Setup ---
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Node.js dependencies for Selenium # Needed for axe-test-fixtures
      run: npm ci --prefix=selenium
      shell: bash
    - name: Start Selenium Fixture Server # Starts server for localhost:8001
      run: python -m http.server 8001 &
      working-directory: selenium/node_modules/axe-test-fixtures/fixtures
      shell: bash
    - name: Wait for Selenium server to start
      run: sleep 5s
      shell: bash
    
    - name: Build with Maven (Running Selenium Tests)
      run: mvn -B package --file pom.xml -t ~/.m2/toolchains.xml
    - name: List Surefire Reports Directory
      run: ls -R selenium/target/surefire-reports || echo "Surefire reports directory not found or empty."
      shell: bash
      if: always()
    - name: List Generated HTML Reports Directory
      run: ls -R target/a11y-html-reports || echo "HTML reports directory not found or empty." # <--- Corrected path
      shell: bash
      if: always()
    - name: Upload Accessibility Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: accessibility-reports
        path: target/a11y-html-reports/** # <--- Corrected path
