name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'  # Explicitly set to Java 21
        distribution: 'temurin'
        cache: maven
    - name: Verify Java Version
      run: java -version # This step will confirm the active Java version in the logs
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload Accessibility Reports
      uses: actions/upload-artifact@v3
      if: always() # This ensures this step runs eveen if previous steps fail
      with:
        name: accessibility-reports
        # Use a more robust path that includes a wildcard,
        # or ensure the directory exists before uploading.
        path: selenium/target/a11y-html-reports/**
