name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'  # Explicitly set to Java 21
        distribution: 'temurin'
        cache: maven
    - name: Verify Java Version
      run: java -version # This step will confirm the active Java version in the logs
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload Accessibility Reports
      uses: actions/upload-artifact@v3
      with:
        name: accessibility-reports
        path: selenium/target/a11y-html-reports # Path to your generated HTML reports
        # You can also include JSON reports if needed:
        # path: |
        #   selenium/target/a11y-html-reports
        #   selenium/target/a11y-json-reports
