name: Java CI with Maven # This is the workflow name, it should be at the very top

on:
  push:
    branches: [ "main" ] # This is where the branches configuration belongs
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Verify Java Version
      run: java -version
    - name: Set up Maven 3.8.8
      uses: stefanzweifel/setup-maven@v1
      with:
        maven-version: '3.8.8'
    - name: Verify Maven Version
      run: mvn --version
    - name: Create Maven Toolchains file
      run: |
        mkdir -p ~/.m2
        echo "<toolchains>" > ~/.m2/toolchains.xml
        echo "  <toolchain>" >> ~/.m2/toolchains.xml
        echo "    <type>jdk</type>" >> ~/.m2/toolchains.xml
        echo "    <provides>" >> ~/.m2/toolchains.xml
        echo "      <version>21</version>" >> ~/.m2/toolchains.xml
        echo "      <vendor>temurin</vendor>" >> ~/.m2/toolchains.xml
        echo "    </provides>" >> ~/.m2/toolchains.xml
        echo "    <configuration>" >> ~/.m2/toolchains.xml
        echo "      <jdkHome>${JAVA_HOME}</jdkHome>" >> ~/.m2/toolchains.xml
        echo "    </configuration>" >> ~/.m2/toolchains.xml
        echo "  </toolchain>" >> ~/.m2/toolchains.xml
        echo "</toolchains>" >> ~/.m2/toolchains.xml
      shell: bash
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload Accessibility Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: accessibility-reports
        path: selenium/target/a11y-html-reports/**
